_: {
  nixos.configurations.rwslaptop.module = {...}: {
    imports = [
      (
        # Do not modify this file!  It was generated by ‘nixos-generate-config’
        # and may be overwritten by future invocations.  Please make changes
        # to /etc/nixos/configuration.nix instead.
        {
          config,
          lib,
          modulesPath,
          ...
        }: {
          imports = [
            (modulesPath + "/installer/scan/not-detected.nix")
          ];

          boot = {
            initrd = {
              availableKernelModules = ["xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc"];
              kernelModules = [];
              luks.devices."cryptroot".device = "/dev/disk/by-uuid/b59fcce9-a0f4-4ed0-8ef1-96bff52f9dba";
            };
            kernelModules = ["kvm-intel"];
            extraModulePackages = [];
          };

          fileSystems."/" = {
            device = "/dev/mapper/cryptroot";
            fsType = "ext4";
          };

          fileSystems."/boot" = {
            device = "/dev/disk/by-uuid/38E5-4019";
            fsType = "vfat";
            options = ["fmask=0022" "dmask=0022"];
          };

          swapDevices = [];

          nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
          hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
        }
      )
    ];
    boot.initrd.luks.devices.cryptroot.device = "/dev/disk/by-uuid/b59fcce9-a0f4-4ed0-8ef1-96bff52f9dba";
  };
}
