# Set the default model and provider
model = "gpt-5"
model_provider = "azure"
model_reasoning_effort = "high"

# Configure the Azure provider
[model_providers.azure]
name = "Azure"
# Make sure you set the appropriate subdomain for this URL.
base_url = "https://apim.datalab-01.azure.grid.rws.nl/openai/v1"
env_http_headers = { Authorization = "AOAI_TOKEN" }
wire_api = "responses"
model_reasoning_effort = "high"
